### ISSUE TITLE
additional materials, text notes

### ISSUE THREAD

**Issue by bnawras** [foxfrikses/BlackBeltCpp#1]
Hi, I watched the video lectures, but I remember that there were some additional materials, text notes. I would appreciate it if you would share them. Because now this course is available only for old students. I'm interested in black belt.

**Comment by foxfrikses** [comment]
> Hi, I watched the video lectures, but I remember that there were some additional materials, text notes. I would appreciate it if you would share them. Because now this course is available only for old students. I'm interested in black belt.

Hi. This course, as well as the other courses of this specialization, are available on Stepik now.

**Comment by bnawras** [comment]
Indeed, I found [it](https://cppcourse.ru/ ), thanks!
